version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
